version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql-testapidts
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: testapidts
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: testapidts-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testapidts
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppassword
      JWT_SECRET: YOUR_BASE64_SECRET
      APP_BOOTSTRAP_ENABLE: "true"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  db_data: